# Aplicação RAG - Configuração de Implantação

# Arquivo de configuração para implantação do Streamlit
[server]
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
